config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", 
    passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  
  resources :collections do
    put 'toggle_visibility' => 'collections#toggle_visibility', as: :visibility
    put 'sort' => 'collections#sort', as: :sort
    post 'create_header' => 'resources#create_header', as: :create_header
    post 'create_resource' => 'resources#create_by_url', as: :create_resource
    resources :resources do
      put 'move/:new_collection_id' => 'resources#change_parent', as: :move
      put 'copy/:new_collection_id' => 'resources#copy', as: :copy
    end
  end

  get 'hi' => 'landings#index'

  get '/u/:username' => 'users#show', as: :user
  get '/r/:rid' => 'resources#show', as: :resource

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :resources, dependent: :destroy
  belongs_to :user

  validates :name, length: { minimum: 2, maximum: 200 }, allow_blank: false
  validates :description, length: { maximum: 140 }
  paginates_per 30

  scope :visible, -> { where(is_visible: true) }

  default_scope { order(:name) }

  def belongs_to?(user)
    user && self.user_id == user.id
  end

  def find_resource(id)
    self.resources.where id: id
  end

  def resources_with_thumbnail
    resources.with_thumbnail
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :get_user
  before_action :get_collection, only: [:show, :edit, :update, :destroy, :toggle_visibility, :sort]
  before_action only: [:edit, :update, :destroy, :toggle_visibility, :sort] do
    require_owner @collection.user
  end
  before_action :require_user_signed_in, except: [:index, :show]
  before_action :check_visibility, only: [:show]
  before_action :user_owned_collections, only: [:show]

  def index
    # @collections = Collection.order(updated_at: :desc).page params[:page]
    # respond_to do |format|
    #   format.html {}
    #   format.js {}
    # end
    if current_user.present?
      redirect_to user_path(current_user.username)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    @resources = @collection.resources.order(:priority, :created_at)
    @current_resource = Resource.where(id:params[:rid]).first if params[:rid]
    @partial_url = request.original_url

    if @current_resource
      idx = @resources.index @current_resource
      if idx + 1 <= @resources.count
        @next_resource = @resources[idx + 1]
      end
      if idx > 0
        @prev_resource = @resources[idx - 1]
      end
    end
    
    respond_to do |format|
      format.html {}
      # format.js {}
    end
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new create_params
    @collection.user = current_user
    if @collection.save
      redirect_to collection_path(@collection.id)
    else
      flash[:error] = @collection.errors.full_messages.join(', ')
      redirect_to :back
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @collection.update(create_params)
        format.html { redirect_to action: :show }
        format.js {}
      else
        format.html { redirect_to action: :show }
        format.js { render status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.delete
    redirect_to :root
  end

  def toggle_visibility
    begin
      @collection.toggle! :is_visible
    rescue => e
      puts e
    end
    visibility = @collection.is_visible?

    respond_to do |format|
      format.js {}
    end
  end

  def sort
    if params[:resource].present? && params[:resource].kind_of?(Array)
      params[:resource].each_with_index do |id, i|
        @collection.find_resource(id).first.update_attribute(:priority, i)
      end
    end

    respond_to do |format|
      format.js { render }
    end
  end

  private
  def get_collection
    begin
      @collection = Collection.find params[:id] || params[:collection_id]  
    rescue => e
      puts e
      redirect_to :root
    end
  end

  def get_user
    @user = current_user
  end

  def create_params
    params.require(:collection).permit(:name, :description, :is_visible)
  end

  def check_visibility
    if !@collection.is_visible? && (!current_user.present? || @collection.user.id != current_user.id)
      flash[:notice] = 'This collection is private, only author can access it.'
      redirect_to :root
    end
  end

  def user_owned_collections
    if current_user
      @owned_collections = current_user.collections
    else
      @owned_collections = []
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
  def collection_subtitle(collection)
    haml_tag :div, class: 'subtitle' do

      if collection.description.present?
        haml_tag :div, class: 'collection_subtitle_description' do
          haml_tag :a, href: "#{collection_path(collection.id)}" do
            haml_concat collection.description
          end
        end
      end
    end
  end

  def collection_info(collection, show_user=true)
    haml_tag :div, class: 'subtitle' do
      if show_user
        haml_tag :a, href: "#{user_path(collection.user.username)}" do
          haml_concat collection.user.name
        end
        haml_concat ' · '
      end

      haml_concat "#{collection.resources.count} items"
      haml_concat ' · '
      haml_concat "#{time_ago_in_words(collection.updated_at)} ago"
    end
  end

  def difficulty_btn(difficulty, isSelected=false)
    btn_class = 'btn-large btn-difficulty'
    btn_class += ' selected' if isSelected
    haml_tag :button, class: btn_class, :'data-difficulty' => difficulty.downcase() do
      haml_concat difficulty
    end
  end 

  def is_user_controller?(controller)
    controller == 'users'
  end
end

app/views/collections/_collection.html.haml
.collection.col-50>
  .collection_title
    %a{href: "#{collection_path(collection.id)}"}
      = collection.name
  .collection_subtitle
    - collection_subtitle(collection)
  .collection_thumbnails
    = link_to collection_path(collection) do
      - collection.resources_with_thumbnail.last(4).each do |r|
        .collection_thumbnail{style: "background-image:url(#{r.thumbnail})"}>
  .collection_info
    - collection_info(collection, !is_user_controller?(params[:controller]) )

app/views/collections/_load_more.js.haml
$('.collections').append("#{j(render @collections)}");
$('#paginator').html("#{j(link_to_next_page @collections, '<div class="btn-large">more collections</div>'.html_safe, remote: true)}");

app/views/collections/edit.html.haml
.content
	= form_for @collection, remote: true do |f|
		.row.toolbar
			.col-100
				= f.button 'Cancel', class: 'btn-small btn-cancel right', :'data-dest' => "#{collection_path(@collection)}"
				= f.submit 'Save', class: 'btn-small right'
		.row
			.col-100
				= f.text_field :name, value: @collection.name
		.row
			.col-100
				= f.text_area :description, value: @collection.description
		.row.document-buttons
			.col-100
				= link_to '<div class="resource-btn">+ Text</div>'.html_safe, new_collection_resource_path(@collection.id, mime: 'text')
				= link_to '<div class="resource-btn">+ Video</div>'.html_safe, new_collection_resource_path(@collection.id, mime: 'video')
				= link_to '<div class="resource-btn">+ Link</div>'.html_safe, new_collection_resource_path(@collection.id, mime: 'link')
		- @collection.resources.each do |r|
			.row.document.deletable{id: "resource-#{r.id}"}
				.col-10
					- resource_icon(r.mime)
				.title.col-80>
					= link_to r.title, collection_resource_path(@collection, r), title: r.title
				.remove.col-10
					= link_to icon('trash'), collection_resource_path(@collection, r), remote: true, method: :delete, class: 'right'

app/views/collections/index.html.haml
- print_collection_create_button(@collection)

.content
	.collection-header
		.brand-row.row
			.col-100.brand>
				Collk
	.banner
		Newest Collections

	.collection-container
		.collections
			= render(@collections)
		#paginator
			= link_to_next_page @collections, '<div class="btn-large">more collections</div>'.html_safe, remote: true

app/views/collections/new.html.haml
.content
  = form_for @collection do |f|
    .row
      .col-100
        = f.text_field :name, placeholder: "Collection Name"
    .row
      .col-100
        visibility: 
        = select(:collection, :is_visible, [['public', true], ['only me', false]])
    .row
      .col-100
        = f.text_area :description, placeholder: "Description here (optional)"
    .row
      .col-100
        = f.submit 'Create', class: 'btn-normal'

app/views/collections/show.html.haml
- html_title(@collection.name.first(50))
- html_description(@collection.description)
- content_for :collection_show_menu_header do
  - @collection.name

- visibility_class = @collection.is_visible? ? '_is_public' : '_is_private'
#collection.content{class: visibility_class}
  .row
    %span.backLink
      = link_to "#{user_path(@collection.user.username)}", id: 'navbar_back' do
        = " #{icon('arrow-left')} Go Back".html_safe
    %span.visibility.right>
      - message_to_public = 'Change visibility to “public” ?'
      - message_to_private = 'Change visibility to “only me” ?'
      - confirm_message = @collection.is_visible? ? message_to_private : message_to_public
      - if @collection.belongs_to? current_user
        = link_to collection_visibility_path(@collection), :'data-confirm' => confirm_message, method: 'put', remote: true, id: "collection-visibility-#{@collection.id}", :'data-modal' => 'true', :'data-message-to-public' => message_to_public, :'data-message-to-private' => message_to_private, class: 'right' do 
          .collection_is_public_visibility
            = "#{icon('globe')}".html_safe
          .collection_is_private_visibility
            = "#{icon('lock')}".html_safe
      - else
        .collection_is_public_visibility
          = "#{icon('globe')}".html_safe
        .collection_is_private_visibility
          = "#{icon('lock')}".html_safe
    - if @collection.belongs_to?(current_user)
      = link_to collection_path(@collection.id), method: :delete, :'data-modal' => 'true', :'data-confirm' => "Delete collection - “#{@collection.name}” ?", class: 'right', id: "collection-delete-#{@collection.id}" do
        %span.btn-delete
          = icon('trash')

  .collection-header
    .row
      .col-90.title>
        - if @collection.belongs_to?(current_user)
          = form_for @collection, remote:true, html: {class: 'no-margin editable'} do |f|
            = f.text_field :name
            .saved-icon
              = icon('check')
        - else
          = @collection.name
  .document.row
    .collection_description.col-100
      - if @collection.belongs_to?(current_user)
        = form_for @collection, remote:true, html: {class: 'no-margin editable'} do |f|
          = f.text_field :description, placeholder: 'Description (optional)'
          .saved-icon
            = icon('check')
      - else
        = @collection.description

  - if @collection.belongs_to?(current_user)
    .row.document-buttons
      .col-100
        = link_to "<div class=\"btn-small\">#{icon('plus')} Article</div>".html_safe, new_collection_resource_path(@collection.id, mime: 'text')
        %span.collection_newResource
          = link_to "<div class=\"btn-small\">#{icon('plus')} Link</div>".html_safe, new_collection_resource_path(@collection.id, mime: 'link')

  .resourceList{:'data-collection-id' => @collection.id}
    .resourceList_item
      - if @collection.belongs_to? @user
        = render partial: 'resources/new_header'
    .sortable
      = render @resources

app/views/collections/toggle_visibility.js.haml
$('#collection').removeClass('_is_public').removeClass('_is_private');
link = $("#collection-visibility-#{@collection.id}");

- if @collection.is_visible?
  $('#collection').addClass('_is_public');
  link.attr('data-confirm', link.attr('data-message-to-private'));
- else
  $('#collection').addClass('_is_private');
  link.attr('data-confirm', link.attr('data-message-to-public'));