config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", 
    passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  
  resources :collections do
    put 'toggle_visibility' => 'collections#toggle_visibility', as: :visibility
    put 'sort' => 'collections#sort', as: :sort
    post 'create_header' => 'resources#create_header', as: :create_header
    post 'create_resource' => 'resources#create_by_url', as: :create_resource
    resources :resources do
      put 'move/:new_collection_id' => 'resources#change_parent', as: :move
      put 'copy/:new_collection_id' => 'resources#copy', as: :copy
    end
  end

  get 'hi' => 'landings#index'

  get '/u/:username' => 'users#show', as: :user
  get '/r/:rid' => 'resources#show', as: :resource

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/partials/_dialog.html.haml
#confirmDialog
  #confirmDialog_text
  #confirmDialog_buttons
    #confirmDialog_buttons_cancel
      .btn-small.btn-no
        no
    #confirmDialog_buttons_confirm
      .btn-small.btn-yes
        yes

app/views/partials/_lightbox.html.haml
- if @current_resource
  %input{id: 'lightbox-markdownDescription', type:'hidden', value: get_description(@current_resource) }
  #lightbox_player.lightbox_player.prevent-quit
    %h1.lightbox_player_title
      = @current_resource.title
      .lightbox_player_subtitle
        - if @current_resource.is_text?
          - if @collection.belongs_to?(current_user)
            = link_to edit_collection_resource_path(@collection, @current_resource) do
              = icon('edit')
              Edit Article
        - elsif @current_resource.is_header?
          // do nothing
        - else
          = link_to @current_resource.url, target: '_blank' do
            = icon('external-link')
            View Original
    .lightbox_player_content
      - if @current_resource.thumbnail.present? && @current_resource.should_present_thumbnail?
        = link_to image_tag(@current_resource.thumbnail), @current_resource.url, target: '_blank'

      .lightbox_player_html
        - if @current_resource.content.present?
          = @current_resource.content.html_safe
        - elsif @current_resource.embedded_html.present?
          = @current_resource.embedded_html.html_safe
        - elsif @current_resource.description.present?
          = @current_resource.description.html_safe
      - if @current_resource.is_link? && !@current_resource.content.present? && !@current_resource.embedded_html.present? && @current_resource.description.present?
        .lightbox_player_subtitle
          = link_to "See More", @current_resource.url, target: '_blank'
  // translate markdown
  - if @current_resource.is_text?
    :javascript
      $('#lightbox._is_text .lightbox_player_html').html(marked(decodeURIComponent($('#lightbox-markdownDescription').val()), {breaks: true}));

app/views/partials/_lightbox_navigator.html.haml
- if @prev_resource.present?
  #lightbox_previous_button.prevent-quit
    = link_to resource_path(@prev_resource.id), remote: true do
      .btn-round.btn-prev
        = icon('angle-left')

- if @next_resource.present?
  #lightbox_next_button.prevent-quit
    = link_to resource_path(@next_resource.id), remote: true do
      .btn-round.btn-next
        = icon('angle-right')

app/views/partials/_lightbox_next_prev_buttons.html.haml
- if @prev_resource.present?
  #lightbox_previous_button.prevent-quit
    = link_to resource_path(@prev_resource.id), remote: true do
      .btn-round.btn-prev
        = icon('angle-left')

- if @next_resource.present?
  #lightbox_next_button.prevent-quit
    = link_to resource_path(@next_resource.id), remote: true do
      .btn-round.btn-next
        = icon('angle-right')

app/views/partials/_menu.html.haml
#menu.sideMenu
  #user_show_menu_header
    = yield :user_show_menu_header
  #collection_show_menu_header
    = yield :collection_show_menu_header
  %ul
    - if current_user
      %li.sideMenu_item.col-80>
        = link_to icon('list'), user_path(current_user.username), class: 'sideMenu_link'
      %li.sideMenu_item.col-20.text-right>
        = link_to icon('sign-out'), destroy_user_session_path, method: 'DELETE', class: 'sideMenu_link'
    - else
      %li.sideMenu_item
        = link_to icon('sign-in'), new_user_session_path, class: 'sideMenu_link'