config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", 
    passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  
  resources :collections do
    put 'toggle_visibility' => 'collections#toggle_visibility', as: :visibility
    put 'sort' => 'collections#sort', as: :sort
    post 'create_header' => 'resources#create_header', as: :create_header
    post 'create_resource' => 'resources#create_by_url', as: :create_resource
    resources :resources do
      put 'move/:new_collection_id' => 'resources#change_parent', as: :move
      put 'copy/:new_collection_id' => 'resources#copy', as: :copy
    end
  end

  get 'hi' => 'landings#index'

  get '/u/:username' => 'users#show', as: :user
  get '/r/:rid' => 'resources#show', as: :resource

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  has_many :collections

  validates :username,
    uniqueness: { :case_sensitive => false }, 
    format: { with: /\A[a-zA-Z0-9]+\Z/ }

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
    resource.collections << Collection.create({name: "#{@user.username}'s inbox", description: 'My first collection'})
    resource.save
    # redirect_to :back unless resource.save
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find params[:id]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.where(username: params[:username]).first

    if @user.present?
      if user_signed_in? && @user == current_user
        @collections = @user.collections.order(:name).page params[:page]
      else
        @collections = @user.collections.visible.order(:name).page params[:page]
      end

      respond_to do |format|
        format.html {}
        format.js { render partial: 'collections/load_more' }
      end
    else
      redirect_to :root 
    end
	end
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
  def is_current_user?(user)
    user && current_user && user.id == current_user.id
  end
end

app/views/users/show.html.haml
- title = "#{@user.username}'s collections"
- html_title(title.first(50))

- content_for :user_show_menu_header do
  - title

.content
  .collection-header
    .brand-row.row
      .col-100.brand>
        = title
  - if is_current_user?(@user)
    .collection-new
      = link_to new_collection_path, class: '' do
        = icon('plus-square')
        New Collection
  .collection-container
    .collections
      - if is_current_user?(@user)
        - empty_string = '<div class="collections_empty"><div>Create a collcetion now. It could be food recipes, photos, tutorial videos or any links!</div><a href="'+new_collection_path()+'"><div class="btn-large btn-success">'+icon('plus')+' Create my first collection</div></a></div>'
      - else
        - empty_string = '<div class="collections_empty">There is no collection yet.</div>'
      = render(@collections) || empty_string.html_safe
    #paginator
      = link_to_next_page @collections, '<div class="btn-large">more collections</div>'.html_safe, remote: true