config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", 
    passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'
  
  resources :collections do
    put 'toggle_visibility' => 'collections#toggle_visibility', as: :visibility
    put 'sort' => 'collections#sort', as: :sort
    post 'create_header' => 'resources#create_header', as: :create_header
    post 'create_resource' => 'resources#create_by_url', as: :create_resource
    resources :resources do
      put 'move/:new_collection_id' => 'resources#change_parent', as: :move
      put 'copy/:new_collection_id' => 'resources#copy', as: :copy
    end
  end

  get 'hi' => 'landings#index'

  get '/u/:username' => 'users#show', as: :user
  get '/r/:rid' => 'resources#show', as: :resource

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/views/resources/_new_header.html.haml
.resourceList_newElement
  .resourceList_detectingArea
  .resourceList_newElement_row.row
    .icon-column>
      .btn-square.btn-new-element
        = icon('plus')
    .col-80
      = form_tag collection_create_header_path(@collection), class:'collection_cerateByUrlForm', remote: true do
        = text_field_tag :title, '', placeholder: 'Type header here', class: 'collection_createByUrlForm_url'
        = label_tag '"Enter" to create header'

app/views/resources/_resource.html.haml
- draggable_class = 'draggable' if @collection.belongs_to? @user
.resourceList_item.deletable{id: "resource-#{resource.id}", class: "resourceList_#{resource.mime}", :'data-resource-id' => "#{resource.id}"}
  .row
    .icon-column{class: draggable_class}>
      .animation-icon.animation-icon-before
        - resource_icon(resource.mime)
      .animation-icon.animation-icon-after
        .btn-resource
          = icon('arrows-v')
    .resourceList_title.col-80>
      - link = resource.is_fulltext? ? collection_resource_path(@collection, resource) : resource.url
      .resourceList_title_show
        - print_title(resource)
      .resourceList_title_edit
        .col-80>
          = form_for resource, url: collection_resource_path(@collection, resource), method: 'PATCH', remote: true do |f|
            = f.text_field :title
        .col-20.tip
          "Enter" to update
        
    .resourceList_tools.col-10
      - print_resource_tools(@collection, resource)
      
  - if resource.thumbnail.present? || resource.description.present?
    .resourceList_preview
      .icon-column>
      - if resource.thumbnail.present?
        .resourceList_preview_thumbnails.col-20>
          - print_thumbnail_link(resource)
        - if resource.description.present?
          .inline-block.col-60>
            .resourceList_preview_digest
              - print_description(resource) unless resource.mime == 'photo'
      - elsif resource.description.present?
        .inline-block.col-80>
          .resourceList_preview_digest
            - link = resource.is_fulltext? ? collection_resource_path(resource.collection, resource) : resource.url
            - print_description(resource)
  .row
    .icon-column>
    .resourceList_bottomTools
      - if @owned_collections && @owned_collections.count > 1 && resource.mime != 'header'
        - if resource.collection.belongs_to?(@user)
          move to
        - else
          copy to

        %select{class: 'selectable-resource', :'data-resource-id' => resource.id, :'data-collection-id' => @collection.id}
          - owned_collections_exclude_self = @owned_collections.reject{|c| c.id == @collection.id }
          - owned_collections_exclude_self.each do |c|
            %option{value: c.id}
              = c.name.first(50)
        - if resource.collection.belongs_to? @user
          = link_to collection_resource_move_path(@collection, resource, owned_collections_exclude_self.first.id), method: 'put', id: "resource-moveto-#{resource.id}", remote: true do
            .btn-square
              = icon('arrow-right')
        - else
          = link_to collection_resource_copy_path(@collection, resource, owned_collections_exclude_self.first.id), method: 'put', id: "resource-moveto-#{resource.id}", remote: true do
            .btn-square
              = icon('arrow-right')
  - if resource.collection.belongs_to? @user
    = render partial: 'resources/new_header'

app/views/resources/copy.js.haml
$("#resource-moveto-#{resource_id}").parents('.resourceList_bottomTools').text("Copied to #{@new_collection.name}");

app/views/resources/create_header.js.haml
- resource = render partial: 'resources/resource', locals: {resource: @resource}
var newHeaderBtn = $('._is_updating_element').removeClass('_is_updating_element');
if (newHeaderBtn.parents('.sortable').length > 0) { newHeaderBtn.parents('.resourceList_item').after("#{j(resource)}"); } else { newHeaderBtn.parents('.resourceList_item').siblings('.sortable').prepend("#{j(resource)}"); }

var collection_id = $('.resourceList').attr('data-collection-id');
$.ajax({data: $('.sortable').sortable('serialize'),type: 'PUT',url: "/collections/"+collection_id+"/sort"});
$('.sortable').sortable({placeholder: '_is_dragging'});
$('.sortable').sortable('disable');
$('.sortable').disableSelection();

app/views/resources/destroy.js.haml
$("#resource-#{@deleted_id}").remove();

app/views/resources/edit.html.haml
.navbar
  .navbar_item.col-100
    = link_to "<div class=\"btn-large btn-delete\">Delete this item</div>".html_safe, collection_resource_path(@collection.id, @resource.id), method: :delete, class: 'right'

.content
  .backLink
    = link_to collection_path(@collection.id, rid: @resource.id), id: 'navbar_back' do
      = " #{icon('arrow-left')} Go Back".html_safe

  = form_for [@collection, @resource] do |f|
    = f.hidden_field :mime, value: @resource.mime
    = f.text_field :title, placeholder: 'Edit title here', autofocus: true
    - if @resource.mime == 'text'
      .toolbar.row
        .col-100
          = f.button 'H1', id:'h1-btn', class: 'btn-editor btn-edit'
          = f.button 'H2', id:'h2-btn', class: 'btn-editor btn-edit'
          = f.button 'H3', id:'h3-btn', class: 'btn-editor btn-edit'
          = f.button icon('bold'), id:'bold-btn', class: 'btn-editor btn-edit'
          = f.button icon('italic'), id:'italic-btn', class: 'btn-editor btn-edit'
          .div.spacer
          = f.button icon('link'), id:'link-btn', class: 'btn-editor btn-edit'
          = f.button icon('image'), id:'image-btn', class: 'btn-editor btn-edit'
          .div.spacer
          = f.button icon('eye'), id:'preview-btn', class: 'btn-editor'
      = f.text_area :description, id: 'resource-description', placeholder: 'Write something...'
      #markdown-preview

    .submission
      = f.submit 'Update', class: 'btn-normal'

app/views/resources/edit.js.haml
$("#resource-#{@resource.id}").addClass('_is_editable');
$("#resource-#{@resource.id}").find('.resourceList_title_edit input').focus();

app/views/resources/move.js.haml
$("#resource-moveto-#{resource_id}").parents('.resourceList_item').remove();

app/views/resources/new.html.haml
.content
	.backLink
		= link_to "#{collection_path(@collection.id)}", id: 'navbar_back' do
			= "	#{icon('arrow-left')} Go Back".html_safe
	= form_for [@collection, @resource] do |f|
		= f.hidden_field :mime, value: @mime
		- if @mime == 'text'
			= f.text_field :title, placeholder: 'Edit title here', autofocus: true
			.toolbar.row
				.col-100
					= f.button 'H1', id:'h1-btn', class: 'btn-editor btn-edit'
					= f.button 'H2', id:'h2-btn', class: 'btn-editor btn-edit'
					= f.button 'H3', id:'h3-btn', class: 'btn-editor btn-edit'
					= f.button icon('bold'), id:'bold-btn', class: 'btn-editor btn-edit'
					= f.button icon('italic'), id:'italic-btn', class: 'btn-editor btn-edit'
					.div.spacer
					= f.button icon('link'), id:'link-btn', class: 'btn-editor btn-edit'
					= f.button icon('image'), id:'image-btn', class: 'btn-editor btn-edit'
					.div.spacer
					= f.button icon('eye'), id:'preview-btn', class: 'btn-editor'
			= f.text_area :description, id: 'resource-description', placeholder: 'Write something...'
			#markdown-preview
		- if @mime == 'link' || @mime == 'video'
			= f.text_field :url, placeholder: 'Post url here', id: 'link-url', autofocus: true
			= f.hidden_field :title, id: 'link-title'
			= f.hidden_field :description, id: 'link-description'

		.submission
			= f.submit 'Create', class: 'btn-normal'
		.preview

app/views/resources/show.js.haml
- if @current_resource.present?
  $('body').addClass('_is_lightbox_mode');
  - lightbox = render(partial: "partials/lightbox")
  - lightbox_navigator = render(partial: "partials/lightbox_navigator")
  $('#lightbox').removeClass().addClass("_is_#{@current_resource.mime}");
  $('#lightbox .lightbox_loader').html("#{j(lightbox.html_safe)}");

  $('#lightbox_next_prev_buttons').html("#{j(lightbox_navigator.html_safe)}");
  $('#lightbox_previous_button').css('top', $(window).innerHeight()/2);
  $('#lightbox_next_button').css('top', $(window).innerHeight()/2);
  
  window.history.pushState(null, 'GS', "#{@partial_url}");

  // update lightbox class
  - lightbox_class = @current_resource.description.present? ?  '' : '_has_no_description'
  - lightbox_class = @current_resource.thumbnail.present? ? lightbox_class : '_has_no_thumbnail ' + lightbox_class
  - lightbox_class = " _is_#{@current_resource.mime} " + lightbox_class
  - lightbox_class = @current_resource.is_title_only? ? '_is_title_only ' + lightbox_class : lightbox_class
  $('#lightbox').removeClass().addClass("#{j(lightbox_class)}");

app/views/resources/update.js.haml
link = $("#resource-#{@resource.id}").find('.resourceList_title_show a')
link.attr('title', "#{@resource.title}").text("#{@resource.title}");
$("#resource-#{@resource.id}").removeClass('_is_editable');